CXX = g++
CXXFLAGS = -g -std=c++14 -Wall -Werror=return-type -Werror=uninitialized -Wno-sign-compare

HEADERS = random-password.hpp
OBJECTS = test/test-cases.o
TARGET = test_executable

all: $(TARGET)

$(TARGET): $(OBJECTS)
	$(CXX) -o $@ $^

run_test: $(TARGET)
	./$(TARGET)

%.o: test/%.cpp $(HEADERS)
	$(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
	rm -f $(OBJECTS) $(TARGET)