CXX = g++
CXXFLAGS = -g -std=c++14 -Wall -Werror=return-type -Werror=uninitialized -Wno-sign-compare

HEADERS = random-password.hpp
OBJECTS = test/test.o
TARGET = test

all: $(TARGET)

$(TARGET): $(OBJECTS)
    $(CXX) -o $@ $^

test: $(TARGET)
    ./$(TARGET)

%.o: test/%.cpp $(HEADERS)
    $(CXX) $(CXXFLAGS) -c -o $@ $<

clean:
    rm -f $(OBJECTS) $(TARGET)